CREATE TABLE address_code(code int, area VARCHAR(10),city VARCHAR(10));
INSERT INTO address_code (code,area,city) VALUES (11010,'서울특별시','종로구');
INSERT INTO address_code (code,area,city) VALUES (11020,'서울특별시','중구');
INSERT INTO address_code (code,area,city) VALUES (11030,'서울특별시','용산구');
INSERT INTO address_code (code,area,city) VALUES (11040,'서울특별시','성동구');
INSERT INTO address_code (code,area,city) VALUES (11050,'서울특별시','광진구');
INSERT INTO address_code (code,area,city) VALUES (11060,'서울특별시','동대문구');
INSERT INTO address_code (code,area,city) VALUES (11070,'서울특별시','중랑구');
INSERT INTO address_code (code,area,city) VALUES (11080,'서울특별시','성북구');
INSERT INTO address_code (code,area,city) VALUES (11090,'서울특별시','강북구');
INSERT INTO address_code (code,area,city) VALUES (11100,'서울특별시','도봉구');
INSERT INTO address_code (code,area,city) VALUES (11110,'서울특별시','노원구');
INSERT INTO address_code (code,area,city) VALUES (11120,'서울특별시','은평구');
INSERT INTO address_code (code,area,city) VALUES (11130,'서울특별시','서대문구');
INSERT INTO address_code (code,area,city) VALUES (11140,'서울특별시','마포구');
INSERT INTO address_code (code,area,city) VALUES (11150,'서울특별시','양천구');
INSERT INTO address_code (code,area,city) VALUES (11160,'서울특별시','강서구');
INSERT INTO address_code (code,area,city) VALUES (11170,'서울특별시','구로구');
INSERT INTO address_code (code,area,city) VALUES (11180,'서울특별시','금천구');
INSERT INTO address_code (code,area,city) VALUES (11190,'서울특별시','영등포구');
INSERT INTO address_code (code,area,city) VALUES (11200,'서울특별시','동작구');
INSERT INTO address_code (code,area,city) VALUES (11210,'서울특별시','관악구');
INSERT INTO address_code (code,area,city) VALUES (11220,'서울특별시','서초구');
INSERT INTO address_code (code,area,city) VALUES (11230,'서울특별시','강남구');
INSERT INTO address_code (code,area,city) VALUES (11240,'서울특별시','송파구');
INSERT INTO address_code (code,area,city) VALUES (11250,'서울특별시','강동구');
INSERT INTO address_code (code,area,city) VALUES (21010,'부산광역시','중구');
INSERT INTO address_code (code,area,city) VALUES (21020,'부산광역시','서구');
INSERT INTO address_code (code,area,city) VALUES (21030,'부산광역시','동구');
INSERT INTO address_code (code,area,city) VALUES (21040,'부산광역시','영도구');
INSERT INTO address_code (code,area,city) VALUES (21050,'부산광역시','부산진구');
INSERT INTO address_code (code,area,city) VALUES (21060,'부산광역시','동래구');
INSERT INTO address_code (code,area,city) VALUES (21070,'부산광역시','남구');
INSERT INTO address_code (code,area,city) VALUES (21080,'부산광역시','북구');
INSERT INTO address_code (code,area,city) VALUES (21090,'부산광역시','해운대구');
INSERT INTO address_code (code,area,city) VALUES (21100,'부산광역시','사하구');
INSERT INTO address_code (code,area,city) VALUES (21110,'부산광역시','금정구');
INSERT INTO address_code (code,area,city) VALUES (21120,'부산광역시','강서구');
INSERT INTO address_code (code,area,city) VALUES (21130,'부산광역시','연제구');
INSERT INTO address_code (code,area,city) VALUES (21140,'부산광역시','수영구');
INSERT INTO address_code (code,area,city) VALUES (21150,'부산광역시','사상구');
INSERT INTO address_code (code,area,city) VALUES (21310,'부산광역시','기장군');
INSERT INTO address_code (code,area,city) VALUES (22010,'대구광역시','중구');
INSERT INTO address_code (code,area,city) VALUES (22020,'대구광역시','동구');
INSERT INTO address_code (code,area,city) VALUES (22030,'대구광역시','서구');
INSERT INTO address_code (code,area,city) VALUES (22040,'대구광역시','남구');
INSERT INTO address_code (code,area,city) VALUES (22050,'대구광역시','북구');
INSERT INTO address_code (code,area,city) VALUES (22060,'대구광역시','수성구');
INSERT INTO address_code (code,area,city) VALUES (22070,'대구광역시','달서구');
INSERT INTO address_code (code,area,city) VALUES (22310,'대구광역시','달성군');
INSERT INTO address_code (code,area,city) VALUES (23010,'인천광역시','중구');
INSERT INTO address_code (code,area,city) VALUES (23020,'인천광역시','동구');
INSERT INTO address_code (code,area,city) VALUES (23040,'인천광역시','연수구');
INSERT INTO address_code (code,area,city) VALUES (23050,'인천광역시','남동구');
INSERT INTO address_code (code,area,city) VALUES (23060,'인천광역시','부평구');
INSERT INTO address_code (code,area,city) VALUES (23070,'인천광역시','계양구');
INSERT INTO address_code (code,area,city) VALUES (23080,'인천광역시','서구');
INSERT INTO address_code (code,area,city) VALUES (23090,'인천광역시','미추홀구');
INSERT INTO address_code (code,area,city) VALUES (23310,'인천광역시','강화군');
INSERT INTO address_code (code,area,city) VALUES (23320,'인천광역시','옹진군');
INSERT INTO address_code (code,area,city) VALUES (24010,'광주광역시','동구');
INSERT INTO address_code (code,area,city) VALUES (24020,'광주광역시','서구');
INSERT INTO address_code (code,area,city) VALUES (24030,'광주광역시','남구');
INSERT INTO address_code (code,area,city) VALUES (24040,'광주광역시','북구');
INSERT INTO address_code (code,area,city) VALUES (24050,'광주광역시','광산구');
INSERT INTO address_code (code,area,city) VALUES (25010,'대전광역시','동구');
INSERT INTO address_code (code,area,city) VALUES (25020,'대전광역시','중구');
INSERT INTO address_code (code,area,city) VALUES (25030,'대전광역시','서구');
INSERT INTO address_code (code,area,city) VALUES (25040,'대전광역시','유성구');
INSERT INTO address_code (code,area,city) VALUES (25050,'대전광역시','대덕구');
INSERT INTO address_code (code,area,city) VALUES (26010,'울산광역시','중구');
INSERT INTO address_code (code,area,city) VALUES (26020,'울산광역시','남구');
INSERT INTO address_code (code,area,city) VALUES (26030,'울산광역시','동구');
INSERT INTO address_code (code,area,city) VALUES (26040,'울산광역시','북구');
INSERT INTO address_code (code,area,city) VALUES (26310,'울산광역시','울주군');
INSERT INTO address_code (code,area,city) VALUES (29010,'세종특별자치시','세종시');
INSERT INTO address_code (code,area,city) VALUES (31010,'경기도','수원시');
INSERT INTO address_code (code,area,city) VALUES (31011,'경기도','수원시 장안구');
INSERT INTO address_code (code,area,city) VALUES (31012,'경기도','수원시 권선구');
INSERT INTO address_code (code,area,city) VALUES (31013,'경기도','수원시 팔달구');
INSERT INTO address_code (code,area,city) VALUES (31014,'경기도','수원시 영통구');
INSERT INTO address_code (code,area,city) VALUES (31020,'경기도','성남시');
INSERT INTO address_code (code,area,city) VALUES (31021,'경기도','성남시 수정구');
INSERT INTO address_code (code,area,city) VALUES (31022,'경기도','성남시 중원구');
INSERT INTO address_code (code,area,city) VALUES (31023,'경기도','성남시 분당구');
INSERT INTO address_code (code,area,city) VALUES (31030,'경기도','의정부시');
INSERT INTO address_code (code,area,city) VALUES (31040,'경기도','안양시');
INSERT INTO address_code (code,area,city) VALUES (31041,'경기도','안양시 만안구');
INSERT INTO address_code (code,area,city) VALUES (31042,'경기도','안양시 동안구');
INSERT INTO address_code (code,area,city) VALUES (31050,'경기도','부천시');
INSERT INTO address_code (code,area,city) VALUES (31060,'경기도','광명시');
INSERT INTO address_code (code,area,city) VALUES (31070,'경기도','평택시');
INSERT INTO address_code (code,area,city) VALUES (31080,'경기도','동두천시');
INSERT INTO address_code (code,area,city) VALUES (31090,'경기도','안산시');
INSERT INTO address_code (code,area,city) VALUES (31091,'경기도','안산시 상록구');
INSERT INTO address_code (code,area,city) VALUES (31092,'경기도','안산시 단원구');
INSERT INTO address_code (code,area,city) VALUES (31100,'경기도','고양시');
INSERT INTO address_code (code,area,city) VALUES (31101,'경기도','고양시 덕양구');
INSERT INTO address_code (code,area,city) VALUES (31103,'경기도','고양시 일산동구');
INSERT INTO address_code (code,area,city) VALUES (31104,'경기도','고양시 일산서구');
INSERT INTO address_code (code,area,city) VALUES (31110,'경기도','과천시');
INSERT INTO address_code (code,area,city) VALUES (31120,'경기도','구리시');
INSERT INTO address_code (code,area,city) VALUES (31130,'경기도','남양주시');
INSERT INTO address_code (code,area,city) VALUES (31140,'경기도','오산시');
INSERT INTO address_code (code,area,city) VALUES (31150,'경기도','시흥시');
INSERT INTO address_code (code,area,city) VALUES (31160,'경기도','군포시');
INSERT INTO address_code (code,area,city) VALUES (31170,'경기도','의왕시');
INSERT INTO address_code (code,area,city) VALUES (31180,'경기도','하남시');
INSERT INTO address_code (code,area,city) VALUES (31190,'경기도','용인시');
INSERT INTO address_code (code,area,city) VALUES (31191,'경기도','용인시 처인구');
INSERT INTO address_code (code,area,city) VALUES (31192,'경기도','용인시 기흥구');
INSERT INTO address_code (code,area,city) VALUES (31193,'경기도','용인시 수지구');
INSERT INTO address_code (code,area,city) VALUES (31200,'경기도','파주시');
INSERT INTO address_code (code,area,city) VALUES (31210,'경기도','이천시');
INSERT INTO address_code (code,area,city) VALUES (31220,'경기도','안성시');
INSERT INTO address_code (code,area,city) VALUES (31230,'경기도','김포시');
INSERT INTO address_code (code,area,city) VALUES (31240,'경기도','화성시');
INSERT INTO address_code (code,area,city) VALUES (31250,'경기도','광주시');
INSERT INTO address_code (code,area,city) VALUES (31260,'경기도','양주시');
INSERT INTO address_code (code,area,city) VALUES (31270,'경기도','포천시');
INSERT INTO address_code (code,area,city) VALUES (31280,'경기도','여주시');
INSERT INTO address_code (code,area,city) VALUES (31350,'경기도','연천군');
INSERT INTO address_code (code,area,city) VALUES (31370,'경기도','가평군');
INSERT INTO address_code (code,area,city) VALUES (31380,'경기도','양평군');
INSERT INTO address_code (code,area,city) VALUES (32010,'강원도','춘천시');
INSERT INTO address_code (code,area,city) VALUES (32020,'강원도','원주시');
INSERT INTO address_code (code,area,city) VALUES (32030,'강원도','강릉시');
INSERT INTO address_code (code,area,city) VALUES (32040,'강원도','동해시');
INSERT INTO address_code (code,area,city) VALUES (32050,'강원도','태백시');
INSERT INTO address_code (code,area,city) VALUES (32060,'강원도','속초시');
INSERT INTO address_code (code,area,city) VALUES (32070,'강원도','삼척시');
INSERT INTO address_code (code,area,city) VALUES (32310,'강원도','홍천군');
INSERT INTO address_code (code,area,city) VALUES (32320,'강원도','횡성군');
INSERT INTO address_code (code,area,city) VALUES (32330,'강원도','영월군');
INSERT INTO address_code (code,area,city) VALUES (32340,'강원도','평창군');
INSERT INTO address_code (code,area,city) VALUES (32350,'강원도','정선군');
INSERT INTO address_code (code,area,city) VALUES (32360,'강원도','철원군');
INSERT INTO address_code (code,area,city) VALUES (32370,'강원도','화천군');
INSERT INTO address_code (code,area,city) VALUES (32380,'강원도','양구군');
INSERT INTO address_code (code,area,city) VALUES (32390,'강원도','인제군');
INSERT INTO address_code (code,area,city) VALUES (32400,'강원도','고성군');
INSERT INTO address_code (code,area,city) VALUES (32410,'강원도','양양군');
INSERT INTO address_code (code,area,city) VALUES (33020,'충청북도','충주시');
INSERT INTO address_code (code,area,city) VALUES (33030,'충청북도','제천시');
INSERT INTO address_code (code,area,city) VALUES (33040,'충청북도','청주시');
INSERT INTO address_code (code,area,city) VALUES (33041,'충청북도','청주시 상당구');
INSERT INTO address_code (code,area,city) VALUES (33042,'충청북도','청주시 서원구');
INSERT INTO address_code (code,area,city) VALUES (33043,'충청북도','청주시 흥덕구');
INSERT INTO address_code (code,area,city) VALUES (33044,'충청북도','청주시 청원구');
INSERT INTO address_code (code,area,city) VALUES (33320,'충청북도','보은군');
INSERT INTO address_code (code,area,city) VALUES (33330,'충청북도','옥천군');
INSERT INTO address_code (code,area,city) VALUES (33340,'충청북도','영동군');
INSERT INTO address_code (code,area,city) VALUES (33350,'충청북도','진천군');
INSERT INTO address_code (code,area,city) VALUES (33360,'충청북도','괴산군');
INSERT INTO address_code (code,area,city) VALUES (33370,'충청북도','음성군');
INSERT INTO address_code (code,area,city) VALUES (33380,'충청북도','단양군');
INSERT INTO address_code (code,area,city) VALUES (33390,'충청북도','증평군');
INSERT INTO address_code (code,area,city) VALUES (34010,'충청남도','천안시');
INSERT INTO address_code (code,area,city) VALUES (34011,'충청남도','천안시 동남구');
INSERT INTO address_code (code,area,city) VALUES (34012,'충청남도','천안시 서북구');
INSERT INTO address_code (code,area,city) VALUES (34020,'충청남도','공주시');
INSERT INTO address_code (code,area,city) VALUES (34030,'충청남도','보령시');
INSERT INTO address_code (code,area,city) VALUES (34040,'충청남도','아산시');
INSERT INTO address_code (code,area,city) VALUES (34050,'충청남도','서산시');
INSERT INTO address_code (code,area,city) VALUES (34060,'충청남도','논산시');
INSERT INTO address_code (code,area,city) VALUES (34070,'충청남도','계룡시');
INSERT INTO address_code (code,area,city) VALUES (34080,'충청남도','당진시');
INSERT INTO address_code (code,area,city) VALUES (34310,'충청남도','금산군');
INSERT INTO address_code (code,area,city) VALUES (34330,'충청남도','부여군');
INSERT INTO address_code (code,area,city) VALUES (34340,'충청남도','서천군');
INSERT INTO address_code (code,area,city) VALUES (34350,'충청남도','청양군');
INSERT INTO address_code (code,area,city) VALUES (34360,'충청남도','홍성군');
INSERT INTO address_code (code,area,city) VALUES (34370,'충청남도','예산군');
INSERT INTO address_code (code,area,city) VALUES (34380,'충청남도','태안군');
INSERT INTO address_code (code,area,city) VALUES (35010,'전라북도','전주시');
INSERT INTO address_code (code,area,city) VALUES (35011,'전라북도','전주시 완산구');
INSERT INTO address_code (code,area,city) VALUES (35012,'전라북도','전주시 덕진구');
INSERT INTO address_code (code,area,city) VALUES (35020,'전라북도','군산시');
INSERT INTO address_code (code,area,city) VALUES (35030,'전라북도','익산시');
INSERT INTO address_code (code,area,city) VALUES (35040,'전라북도','정읍시');
INSERT INTO address_code (code,area,city) VALUES (35050,'전라북도','남원시');
INSERT INTO address_code (code,area,city) VALUES (35060,'전라북도','김제시');
INSERT INTO address_code (code,area,city) VALUES (35310,'전라북도','완주군');
INSERT INTO address_code (code,area,city) VALUES (35320,'전라북도','진안군');
INSERT INTO address_code (code,area,city) VALUES (35330,'전라북도','무주군');
INSERT INTO address_code (code,area,city) VALUES (35340,'전라북도','장수군');
INSERT INTO address_code (code,area,city) VALUES (35350,'전라북도','임실군');
INSERT INTO address_code (code,area,city) VALUES (35360,'전라북도','순창군');
INSERT INTO address_code (code,area,city) VALUES (35370,'전라북도','고창군');
INSERT INTO address_code (code,area,city) VALUES (35380,'전라북도','부안군');
INSERT INTO address_code (code,area,city) VALUES (36010,'전라남도','목포시');
INSERT INTO address_code (code,area,city) VALUES (36020,'전라남도','여수시');
INSERT INTO address_code (code,area,city) VALUES (36030,'전라남도','순천시');
INSERT INTO address_code (code,area,city) VALUES (36040,'전라남도','나주시');
INSERT INTO address_code (code,area,city) VALUES (36060,'전라남도','광양시');
INSERT INTO address_code (code,area,city) VALUES (36310,'전라남도','담양군');
INSERT INTO address_code (code,area,city) VALUES (36320,'전라남도','곡성군');
INSERT INTO address_code (code,area,city) VALUES (36330,'전라남도','구례군');
INSERT INTO address_code (code,area,city) VALUES (36350,'전라남도','고흥군');
INSERT INTO address_code (code,area,city) VALUES (36360,'전라남도','보성군');
INSERT INTO address_code (code,area,city) VALUES (36370,'전라남도','화순군');
INSERT INTO address_code (code,area,city) VALUES (36380,'전라남도','장흥군');
INSERT INTO address_code (code,area,city) VALUES (36390,'전라남도','강진군');
INSERT INTO address_code (code,area,city) VALUES (36400,'전라남도','해남군');
INSERT INTO address_code (code,area,city) VALUES (36410,'전라남도','영암군');
INSERT INTO address_code (code,area,city) VALUES (36420,'전라남도','무안군');
INSERT INTO address_code (code,area,city) VALUES (36430,'전라남도','함평군');
INSERT INTO address_code (code,area,city) VALUES (36440,'전라남도','영광군');
INSERT INTO address_code (code,area,city) VALUES (36450,'전라남도','장성군');
INSERT INTO address_code (code,area,city) VALUES (36460,'전라남도','완도군');
INSERT INTO address_code (code,area,city) VALUES (36470,'전라남도','진도군');
INSERT INTO address_code (code,area,city) VALUES (36480,'전라남도','신안군');
INSERT INTO address_code (code,area,city) VALUES (37010,'경상북도','포항시');
INSERT INTO address_code (code,area,city) VALUES (37011,'경상북도','포항시 남구');
INSERT INTO address_code (code,area,city) VALUES (37012,'경상북도','포항시 북구');
INSERT INTO address_code (code,area,city) VALUES (37020,'경상북도','경주시');
INSERT INTO address_code (code,area,city) VALUES (37030,'경상북도','김천시');
INSERT INTO address_code (code,area,city) VALUES (37040,'경상북도','안동시');
INSERT INTO address_code (code,area,city) VALUES (37050,'경상북도','구미시');
INSERT INTO address_code (code,area,city) VALUES (37060,'경상북도','영주시');
INSERT INTO address_code (code,area,city) VALUES (37070,'경상북도','영천시');
INSERT INTO address_code (code,area,city) VALUES (37080,'경상북도','상주시');
INSERT INTO address_code (code,area,city) VALUES (37090,'경상북도','문경시');
INSERT INTO address_code (code,area,city) VALUES (37100,'경상북도','경산시');
INSERT INTO address_code (code,area,city) VALUES (37310,'경상북도','군위군');
INSERT INTO address_code (code,area,city) VALUES (37320,'경상북도','의성군');
INSERT INTO address_code (code,area,city) VALUES (37330,'경상북도','청송군');
INSERT INTO address_code (code,area,city) VALUES (37340,'경상북도','영양군');
INSERT INTO address_code (code,area,city) VALUES (37350,'경상북도','영덕군');
INSERT INTO address_code (code,area,city) VALUES (37360,'경상북도','청도군');
INSERT INTO address_code (code,area,city) VALUES (37370,'경상북도','고령군');
INSERT INTO address_code (code,area,city) VALUES (37380,'경상북도','성주군');
INSERT INTO address_code (code,area,city) VALUES (37390,'경상북도','칠곡군');
INSERT INTO address_code (code,area,city) VALUES (37400,'경상북도','예천군');
INSERT INTO address_code (code,area,city) VALUES (37410,'경상북도','봉화군');
INSERT INTO address_code (code,area,city) VALUES (37420,'경상북도','울진군');
INSERT INTO address_code (code,area,city) VALUES (37430,'경상북도','울릉군');
INSERT INTO address_code (code,area,city) VALUES (38030,'경상남도','진주시');
INSERT INTO address_code (code,area,city) VALUES (38050,'경상남도','통영시');
INSERT INTO address_code (code,area,city) VALUES (38060,'경상남도','사천시');
INSERT INTO address_code (code,area,city) VALUES (38070,'경상남도','김해시');
INSERT INTO address_code (code,area,city) VALUES (38080,'경상남도','밀양시');
INSERT INTO address_code (code,area,city) VALUES (38090,'경상남도','거제시');
INSERT INTO address_code (code,area,city) VALUES (38100,'경상남도','양산시');
INSERT INTO address_code (code,area,city) VALUES (38110,'경상남도','창원시');
INSERT INTO address_code (code,area,city) VALUES (38111,'경상남도','창원시 의창구');
INSERT INTO address_code (code,area,city) VALUES (38112,'경상남도','창원시 성산구');
INSERT INTO address_code (code,area,city) VALUES (38113,'경상남도','창원시 마산합포구');
INSERT INTO address_code (code,area,city) VALUES (38114,'경상남도','창원시 마산회원구');
INSERT INTO address_code (code,area,city) VALUES (38115,'경상남도','창원시 진해구');
INSERT INTO address_code (code,area,city) VALUES (38310,'경상남도','의령군');
INSERT INTO address_code (code,area,city) VALUES (38320,'경상남도','함안군');
INSERT INTO address_code (code,area,city) VALUES (38330,'경상남도','창녕군');
INSERT INTO address_code (code,area,city) VALUES (38340,'경상남도','고성군');
INSERT INTO address_code (code,area,city) VALUES (38350,'경상남도','남해군');
INSERT INTO address_code (code,area,city) VALUES (38360,'경상남도','하동군');
INSERT INTO address_code (code,area,city) VALUES (38370,'경상남도','산청군');
INSERT INTO address_code (code,area,city) VALUES (38380,'경상남도','함양군');
INSERT INTO address_code (code,area,city) VALUES (38390,'경상남도','거창군');
INSERT INTO address_code (code,area,city) VALUES (38400,'경상남도','합천군');
INSERT INTO address_code (code,area,city) VALUES (39010,'제주특별자치도','제주시');
INSERT INTO address_code (code,area,city) VALUES (39020,'제주특별자치도','서귀포시');