# 로컬용 profile
# 로컬에서 서버를 구동시키고 postman으로 테스트하고 싶을 떄

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/rg"
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  profiles:
    active: aws

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
