# 로컬용 profile
# 로컬에서 서버를 구동시키고 postman으로 테스트하고 싶을 떄

spring:
  profiles:
    active:
      - common
      - aws
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations:
        - classpath:static/db/bicycle.sql
        - classpath:static/db/address_code.sql
