# 배포용
# 배포 환경에서 가장 먼저 읽는 설정입니다. (application.yml이 아닙니다!)
# DB 관련 정보는 Docker 컨테이너의 환경 변수에서 들어옵니다.
# Cloud에서 실행할 때 aws, security profile을 동시에 실행합니다.
#

spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: "jdbc:mysql://${RDBMS_URL}:3306/rg?serverTimezone=Asia/Seoul"
    username: ${RDBMS_USERNAME}
    password: ${RDBMS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    defer-datasource-initialization: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: never
      data-locations:
        - classpath:static/db/bicycle.sql
        - classpath:static/db/address_code.sql
      schema-locations:
        - classpath:static/db/schema.sql
server:
  port: 8080
logging:
  file:
    path: ${LOG_PATH}
decorator:
  datasource:
    p6spy:
      enable-logging: false
