# 공통 기본 설정
# 다른 profile(prod, test)에서 추가로 덮어쓰는 방식으로 진행합니다.


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/rg"
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
