# 배포용
# DB 관련 정보는 Docker 컨테이너의 환경 변수에서 들어옵니다.
# TODO: 본격적인 배포가 시작되면 jpa DDL 관련 설정 손봐야함

spring:
  datasource:
    url: "jdbc:mysql://${RDBMS_URL}:3306/rg"
    username: ${RDBMS_USERNAME}
    password: ${RDBMS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  port: 80
