# 로컬용 profile
# 로컬에서 서버를 구동시키고 postman으로 테스트하고 싶을 떄

spring:
  main:
    allow-circular-references: true
  datasource:
    url: "jdbc:mysql://localhost:3306/rg"
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  profiles:
    active: aws

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 8f248aa7874df072e8d15b2d0b284108
            client-secret: tbGLY0lEfvxkrgFWfssEaXpWTS73nPJa
            scope: profile_nickname, profile_image
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  header: token
  issuer: prgrms
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 60
