# mysql이 설치된 ubuntu로 빌드(테스트)를 수행합니다.

name: CI - develop

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql version: '8.0'
          mysql database: 'rg'
          mysql user: 'dev'
          mysql password: 'dev'
      - name: Write Security yml
        run: |
          echo ${{ secrets.OAUTH_SECRET }} >> src/main/resources/application-security.yml

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
