name: CI / CD using Docker Hub - main

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # -------CI-------
      # Mysql이 설치된 ubuntu로 빌드(테스트)를 수행합니다.
      - uses: actions/checkout@v3
      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql version: '8.0'
          mysql database: 'rg'
          mysql user: 'dev'
          mysql password: 'dev'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: write new yml file
        run: touch 'src/main/resources/application-aws.yml'
      - name: utilize yaml writer module
        uses: mikefarah/yq@master
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          YML_PATH: src/main/resources/application-aws.yml
        with:
          cmd: |
            yq -i ".cloud.aws.credentials.access-key = strenv(AWS_ACCESS_KEY)" $YML_PATH
            yq -i ".cloud.aws.credentials.secret-key = strenv(AWS_SECRET_KEY)" $YML_PATH
            yq -i ".cloud.aws.region.static = strenv(AWS_S3_REGION)" $YML_PATH
            yq -i ".cloud.aws.s3.bucket = strenv(AWS_S3_BUCKET)" $YML_PATH
            yq -i ".cloud.aws.stack.auto = false" $YML_PATH

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      # -------CD---------
      # Docker 이미지를 빌드 후 Docker Hub를 통해 EC2로 배포합니다.
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build-push Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rg:latest
          context: .
          build-args: |
            PINPOINT_HOST=${{ secrets.PINPOINT_HOST }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: 'asdfasffsadf'
          name: ${{ secrets.SERVER_SSH_KEY_NAME }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{secrets.SERVER_SSH_HOST}} >> ~/.ssh/known_hosts

      - name: Command Cloud to Run New Image
        env:
          SERVER_SCRIPT: ./config/server_script_env
        run: |
          echo '#!/bin/sh' >> $SERVER_SCRIPT
          echo 'RDBMS_URL=${{ secrets.RDBMS_URL }}' >> $SERVER_SCRIPT
          echo 'RDBMS_USERNAME=${{ secrets.RDBMS_USERNAME }}' >> $SERVER_SCRIPT
          echo 'RDBMS_PASSWORD=${{ secrets.RDBMS_PASSWORD }}' >> $SERVER_SCRIPT
          cat ./config/server_script >> $SERVER_SCRIPT
          chmod +x $SERVER_SCRIPT
          ssh -i ~/.ssh/${{ secrets.SERVER_SSH_KEY_NAME }} ${{ secrets.SERVER_SSH_USER }} 'bash -s' < $SERVER_SCRIPT
