name: CI / CD using Dockerhub

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # -------CI-------
      # Mysql이 설치된 ubuntu로 빌드(테스트)를 수행합니다.
      - uses: actions/checkout@v3
      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql version: '8.0'
          mysql database: 'rg'
          mysql user: 'dev'
          mysql password: 'dev'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      # -------CD---------
      # Docker 이미지를 빌드 후 Docker Hub를 통해 EC2로 배포합니다.
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build-push Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: epicblueha/rg:latest
          context: .

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: 'asdfasffsadf'
          name: devcourse-joseph-key-pair.pem

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{secrets.SERVER_SSH_HOST}} >> ~/.ssh/known_hosts

      - name : Command Cloud to Run New Image
        run: |
          echo 'RDBMS_URL=${{ secrets.RDBMS_URL }}' >> ./config/server_script_env
          echo 'RDBMS_USERNAME=${{ secrets.RDBMS_USERNAME }}' >> ./config/server_script_env
          echo 'RDBMS_PASSWORD=${{ secrets.RDBMS_PASSWORD }}' >> ./config/server_script_env
          cat ./config/server_script >> ./config/server_script_env
          chmod +x ./config/server_script_env
          ssh -i ~/.ssh/devcourse-joseph-key-pair.pem ${{ secrets.SERVER_SSH_USER }} 'bash -s' < ./config/server_script_env
